from django.utils.translation import gettext_lazy as _
THEORY_TOPICS = [
    {
        "title": "Big O, Big Theta, Big Omega",
        "short_description": _("Notacionet kryesore për matjen e rritjes së algoritmeve."),
        "details": _("Big O jep kufirin e sipërm, Big Θ jep rritjen e saktë asimptotike dhe Big Ω jep kufirin e poshtëm."),
        "example": _("Një cikël i vetëm mbi n elemente ka Θ(n). Dy cikle të folezuara zakonisht japin Θ(n^2)."),
        "complexity": _("Varet nga struktura e algoritmit."),
        "connection_to_logiclab": _("Tabela e së vërtetës në LogicLab ka O(2^n), sepse çdo variabël dyfishon kombinimet."),
    },
    {
        "title": "Linked List",
        "short_description": _("Strukturë lineare ku çdo nyje ruan vlerën dhe lidhjen me nyjen tjetër."),
        "details": _("Linked List është fleksibël për insertime dhe fshirje, por nuk ofron akses direkt si array."),
        "example": "A -> B -> C -> None",
        "complexity": _("Kërkimi O(n), insertimi në fillim O(1)."),
        "connection_to_logiclab": _("Hapat e qarkut mund të ruhen si sekuencë nyjesh ku çdo hap lidhet me hapin pasues."),
    },
    {
        "title": "Divide and Conquer",
        "short_description": _("Ndarje e problemit në nënprobleme më të vogla."),
        "details": _("Problemi ndahet, zgjidhen pjesët dhe më pas bashkohen rezultatet."),
        "example": _("Merge Sort ndan listën në dy pjesë dhe i bashkon të renditura."),
        "complexity": _("Shpesh O(n log n), në varësi të ndarjes dhe bashkimit."),
        "connection_to_logiclab": _("Një shprehje Booleane mund të ndahet në nënshprehje që analizohen veçmas."),
    },
    {
        "title": "Greedy Algorithms",
        "short_description": _("Zgjedhja më e mirë lokale në çdo hap."),
        "details": _("Greedy funksionon kur zgjedhjet lokale çojnë në zgjidhje optimale globale."),
        "example": _("Zgjedhja e intervaleve që mbarojnë më herët në problemin activity selection."),
        "complexity": _("Shpesh dominohet nga renditja: O(n log n)."),
        "connection_to_logiclab": _("Në thjeshtim, një heuristikë greedy mund të zgjedhë transformimin që ul më shumë numrin e portave."),
    },
    {
        "title": "Dynamic Programming",
        "short_description": _("Ruajtje e nënrezultateve për të shmangur përsëritjen."),
        "details": _("Përdoret kur problemi ka nënprobleme të mbivendosura dhe strukturë optimale."),
        "example": _("Fibonacci me memoization shmang llogaritje të përsëritura."),
        "complexity": _("Mund të ulë kompleksitetin nga eksponencial në polinomial ose linear."),
        "connection_to_logiclab": _("Vlerësimi i nënshprehjeve të përsëritura mund të ruhet për të shmangur llogaritje të panevojshme."),
    },
    {
        "title": "Binary Search",
        "short_description": _("Kërkim efikas mbi listë të renditur."),
        "details": _("Në çdo hap përgjysmohet hapësira e kërkimit."),
        "example": _("Kërkimi i vlerës 7 në listën [1, 3, 5, 7, 9]."),
        "complexity": "O(log n)",
        "connection_to_logiclab": _("Koncepti i përgjysmimit lidhet me vendimmarrjen binare 0/1 në pemë logjike."),
    },
    {
        "title": "Sorting Algorithms",
        "short_description": _("Algoritme për renditjen e elementeve."),
        "details": _("Insertion, Selection, Quick dhe Merge Sort tregojnë strategji të ndryshme renditjeje."),
        "example": _("Quick Sort përdor pivot, Merge Sort përdor bashkim të renditur."),
        "complexity": _("Nga O(n) në rast të mirë për Insertion deri në O(n log n) për Merge Sort."),
        "connection_to_logiclab": _("Renditja ndihmon në organizimin e mintermave, maxtermave dhe rezultateve të analizës."),
    },
    {
        "title": _("Memoization në LogicLab"),
        "short_description": _("Ruajtja e rezultateve të llogaritura më parë."),
        "details": _("Memoization shmang përsëritjen kur e njëjta nënshprehje shfaqet disa herë."),
        "example": _("Nëse (A & B) shfaqet disa herë, rezultati i saj mund të ruhet për një kombinim të caktuar."),
        "complexity": _("Ul numrin praktik të vlerësimeve, edhe kur tabela mbetet O(2^n)."),
        "connection_to_logiclab": _("Kjo e lidh Dynamic Programming me vlerësimin e shprehjeve Booleane."),
    },
]
