# Generated by Django 6.0.5 on 2026-05-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='circuit_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_explanation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Imazh qarku',
                'verbose_name_plural': 'Imazhe qarqesh',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
