# Generated by Django 6.0.5 on 2026-05-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_expression', models.TextField()),
                ('normalized_expression', models.TextField(blank=True)),
                ('simplified_expression', models.TextField(blank=True)),
                ('variables', models.CharField(blank=True, max_length=255)),
                ('expression_type', models.CharField(blank=True, max_length=40)),
                ('gate_count', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shprehje Booleane',
                'verbose_name_plural': 'Shprehje Booleane',
                'ordering': ['-created_at'],
            },
        ),
    ]
